---
title: "Wannasurf Data Webscrape"
author: "Sachiko Lamen"
date: "7/12/2022"
output: html_document
---

```{r setup, include=FALSE, warning = FALSE, message = FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
library(tidyverse)
library(rvest)
```

#### Begin Scraping 

```{r}
# Web address of Wannasurf zone in Brazil
RioGrandeDoSul_link = "https://www.wannasurf.com/spot/South_America/Brazil/Rio_Grande_do_Sul/index.html"

# Read in html address
RioGrandeDoSul_page = read_html(RioGrandeDoSul_link) 

# Select data table from web and convert into readable format
RioGrandeDoSul_table = RioGrandeDoSul_page %>%
  html_nodes("table#wanna-table") %>%
  html_table() %>% .[[1]]

# **Important, still need to manually enter wave quality and GPS location
```

```{r}
SantaCatarinaSouth_link = "https://www.wannasurf.com/spot/South_America/Brazil/Santa_Catarina/index.html"

SantaCatarinaSouth_page = read_html(SantaCatarinaSouth_link) 

SantaCatarinaSouth_table = SantaCatarinaSouth_page %>%
  html_nodes("table#wanna-table") %>%
  html_table() %>% .[[1]]

###
Florianopolis_link = "https://www.wannasurf.com/spot/South_America/Brazil/Florianopolis/index.html"

Florianopolis_page = read_html(Florianopolis_link) 

Florianopolis_table = Florianopolis_page %>%
  html_nodes("table#wanna-table") %>%
  html_table() %>% .[[1]]

###
SantaCatarinaNorth_link = "https://www.wannasurf.com/spot/South_America/Brazil/Santa_Catarina_North/index.html"

SantaCatarinaNorth_page = read_html(SantaCatarinaNorth_link) 

SantaCatarinaNorth_table = SantaCatarinaNorth_page %>%
  html_nodes("table#wanna-table") %>%
  html_table() %>% .[[1]]

###
RioDeJaneiroNorte_link = "https://www.wannasurf.com/spot/South_America/Brazil/Rio_de_Janeiro_Norte/index.html"

RioDeJaneiroNorte_page = read_html(RioDeJaneiroNorte_link) 

RioDeJaneiroNorte_table = RioDeJaneiroNorte_page %>%
  html_nodes("table#wanna-table") %>%
  html_table() %>% .[[1]]

###
Parana_link = "https://www.wannasurf.com/spot/South_America/Brazil/Parana/index.html"

Parana_page = read_html(Parana_link) 

Parana_table = Parana_page %>%
  html_nodes("table#wanna-table") %>%
  html_table() %>% .[[1]]

###
SaoPauloSouth_link = "https://www.wannasurf.com/spot/South_America/Brazil/Sao_Paulo_South_Coast/index.html"

SaoPauloSouth_page = read_html(SaoPauloSouth_link) 

SaoPauloSouth_table = SaoPauloSouth_page %>%
  html_nodes("table#wanna-table") %>%
  html_table() %>% .[[1]]

###
SaoPauloNorth_link = "https://www.wannasurf.com/spot/South_America/Brazil/Sao_Paulo_North_Coast/index.html"

SaoPauloNorth_page = read_html(SaoPauloNorth_link) 

SaoPauloNorth_table = SaoPauloNorth_page %>%
  html_nodes("table#wanna-table") %>%
  html_table() %>% .[[1]]

###
RioDeJaneiroCity_link = "https://www.wannasurf.com/spot/South_America/Brazil/Rio_de_Janeiro_City/index.html"

RioDeJaneiroCity_page = read_html(RioDeJaneiroCity_link) 

RioDeJaneiroCity_table = RioDeJaneiroCity_page %>%
  html_nodes("table#wanna-table") %>%
  html_table() %>% .[[1]]

###
EsperitoSanto_link = "https://www.wannasurf.com/spot/South_America/Brazil/Espirito_Santo/index.html"

EsperitoSanto_page = read_html(EsperitoSanto_link) 

EsperitoSanto_table = EsperitoSanto_page %>%
  html_nodes("table#wanna-table") %>%
  html_table() %>% .[[1]]

###
BahiaNorte_link = "https://www.wannasurf.com/spot/South_America/Brazil/Bahia_North_Coast/index.html"

BahiaNorte_page = read_html(BahiaNorte_link) 

BahiaNorte_table = BahiaNorte_page %>%
  html_nodes("table#wanna-table") %>%
  html_table() %>% .[[1]]

###
BahiaSul_link = "https://www.wannasurf.com/spot/South_America/Brazil/Bahia_Sul/index.html"

BahiaSul_page = read_html(BahiaSul_link) 

BahiaSul_table = BahiaSul_page %>%
  html_nodes("table#wanna-table") %>%
  html_table() %>% .[[1]]

###
SergipeAlagoas_link = "https://www.wannasurf.com/spot/South_America/Brazil/Sergipe-Alagoas/index.html"

SergipeAlagoas_page = read_html(SergipeAlagoas_link) 

SergipeAlagoas_table = SergipeAlagoas_page %>%
  html_nodes("table#wanna-table") %>%
  html_table() %>% .[[1]]

###
ParaibaPernambucco_link = "https://www.wannasurf.com/spot/South_America/Brazil/Paraiba_Pernambucco/index.html"

ParaibaPernambucco_page = read_html(ParaibaPernambucco_link) 

ParaibaPernambucco_table = ParaibaPernambucco_page %>%
  html_nodes("table#wanna-table") %>%
  html_table() %>% .[[1]]

###
RioGrandeDoNorte_link = "https://www.wannasurf.com/spot/South_America/Brazil/Rio_Grande_Do_Norte/index.html"

RioGrandeDoNorte_page = read_html(RioGrandeDoNorte_link) 

RioGrandeDoNorte_table = RioGrandeDoNorte_page %>%
  html_nodes("table#wanna-table") %>%
  html_table() %>% .[[1]]

###
FernandoDoNoronha_link = "https://www.wannasurf.com/spot/South_America/Brazil/Fernando_do_Noronha/index.html"

FernandoDoNoronha_page = read_html(FernandoDoNoronha_link) 

FernandoDoNoronha_table = FernandoDoNoronha_page %>%
  html_nodes("table#wanna-table") %>%
  html_table() %>% .[[1]]

###
Ceara_link = "https://www.wannasurf.com/spot/South_America/Brazil/Ceara/index.html"

Ceara_page = read_html(Ceara_link) 

Ceara_table = Ceara_page %>%
  html_nodes("table#wanna-table") %>%
  html_table() %>% .[[1]]

###
Maranhao_link = "https://www.wannasurf.com/spot/South_America/Brazil/Maranhao/index.html"

Maranhao_page = read_html(Maranhao_link) 

Maranhao_table = Maranhao_page %>%
  html_nodes("table#wanna-table") %>%
  html_table() %>% .[[1]]

###
Para_link = "https://www.wannasurf.com/spot/South_America/Brazil/Para/index.html"

Para_page = read_html(Para_link) 

Para_table = Para_page %>%
  html_nodes("table#wanna-table") %>%
  html_table() %>% .[[1]]
```

#### End Scraping 
